.\""
.Dd August 13, 2007
.Dt PRTLV 1  
.Os Mac OS X       
.Sh NAME
.Nm prtlv
.Nd Prints a Tag-Length-Value record in human-readable form.
.Sh SYNOPSIS
.Nm
.Ar tlvfile
.Pp
.Sh DESCRIPTION
The
.Nm
command is used to print a Tag-Length-Value (TLV) record in human-readable
form. The TLV is expected to be of the form described in ISO/IEC 7816-4,
meant for use in SmartCard applications. The
.Nm
program is part of the NIST match-on-card testing suite.
.Pp
.Sh EXAMPLES
\'prtlv tlv.raw'
.Pp
would produce output something like this:
.Pp
TAG 0x7F61, Length 65, Value 
    TAG 0x02, Length 1, Value 0x02 
    TAG 0x7F60, Length 28, Value 
        TAG 0xA1, Length 26, Value 
            TAG 0x81, Length 1, Value 0x08 
            TAG 0x82, Length 1, Value 0x02 
            TAG 0x87, Length 2, Value 0xDE AD 
            TAG 0x88, Length 2, Value 0xBE EF 
            TAG 0xB1, Length 10, Value 
                TAG 0x81, Length 2, Value 0x0C 40 
                TAG 0x82, Length 1, Value 0x11 
                TAG 0x83, Length 1, Value 0x00 
    TAG 0x7F60, Length 28, Value 
        TAG 0xA1, Length 26, Value 
            TAG 0x81, Length 1, Value 0x08 
            TAG 0x82, Length 1, Value 0x07 
            TAG 0x87, Length 2, Value 0xBE EF 
            TAG 0x88, Length 2, Value 0xDE AD 
            TAG 0xB1, Length 10, Value 
                TAG 0x81, Length 2, Value 0x0C 40 
                TAG 0x82, Length 1, Value 0x11 
                TAG 0x83, Length 1, Value 0x00 
.Pp
.Sh STANDARDS
``Identification cards - Integrated circuit cards - Part 4: Organization,
security and commands for interchange'',
ISO 7816-4 2005-01-15.
.Pp
.Sh HISTORY
Created August 13th, 2007 by NIST.
